// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pipedreamconnect.proto

package pipedreamconnect

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConnectRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectRequest) Reset()         { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()    {}
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c188de82a668753, []int{0}
}

func (m *ConnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRequest.Unmarshal(m, b)
}
func (m *ConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRequest.Marshal(b, m, deterministic)
}
func (m *ConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRequest.Merge(m, src)
}
func (m *ConnectRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectRequest.Size(m)
}
func (m *ConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRequest proto.InternalMessageInfo

func (m *ConnectRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type AcceptRequest struct {
	Port                 int32    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptRequest) Reset()         { *m = AcceptRequest{} }
func (m *AcceptRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptRequest) ProtoMessage()    {}
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c188de82a668753, []int{1}
}

func (m *AcceptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptRequest.Unmarshal(m, b)
}
func (m *AcceptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptRequest.Marshal(b, m, deterministic)
}
func (m *AcceptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptRequest.Merge(m, src)
}
func (m *AcceptRequest) XXX_Size() int {
	return xxx_messageInfo_AcceptRequest.Size(m)
}
func (m *AcceptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptRequest proto.InternalMessageInfo

func (m *AcceptRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type DisconnectRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectRequest) Reset()         { *m = DisconnectRequest{} }
func (m *DisconnectRequest) String() string { return proto.CompactTextString(m) }
func (*DisconnectRequest) ProtoMessage()    {}
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c188de82a668753, []int{2}
}

func (m *DisconnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectRequest.Unmarshal(m, b)
}
func (m *DisconnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectRequest.Marshal(b, m, deterministic)
}
func (m *DisconnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectRequest.Merge(m, src)
}
func (m *DisconnectRequest) XXX_Size() int {
	return xxx_messageInfo_DisconnectRequest.Size(m)
}
func (m *DisconnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectRequest proto.InternalMessageInfo

func (m *DisconnectRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type RejectRequest struct {
	Port                 int32    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectRequest) Reset()         { *m = RejectRequest{} }
func (m *RejectRequest) String() string { return proto.CompactTextString(m) }
func (*RejectRequest) ProtoMessage()    {}
func (*RejectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c188de82a668753, []int{3}
}

func (m *RejectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectRequest.Unmarshal(m, b)
}
func (m *RejectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectRequest.Marshal(b, m, deterministic)
}
func (m *RejectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectRequest.Merge(m, src)
}
func (m *RejectRequest) XXX_Size() int {
	return xxx_messageInfo_RejectRequest.Size(m)
}
func (m *RejectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RejectRequest proto.InternalMessageInfo

func (m *RejectRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*ConnectRequest)(nil), "pipedreamconnect.ConnectRequest")
	proto.RegisterType((*AcceptRequest)(nil), "pipedreamconnect.AcceptRequest")
	proto.RegisterType((*DisconnectRequest)(nil), "pipedreamconnect.DisconnectRequest")
	proto.RegisterType((*RejectRequest)(nil), "pipedreamconnect.RejectRequest")
}

func init() { proto.RegisterFile("pipedreamconnect.proto", fileDescriptor_8c188de82a668753) }

var fileDescriptor_8c188de82a668753 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0xc8, 0x2c, 0x48,
	0x4d, 0x29, 0x4a, 0x4d, 0xcc, 0x4d, 0xce, 0xcf, 0xcb, 0x4b, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x12, 0x40, 0x17, 0x57, 0xd2, 0xe2, 0xe2, 0x73, 0x86, 0x30, 0x83, 0x52, 0x0b,
	0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x24, 0xb8, 0xd8, 0x13, 0x53, 0x52, 0x8a, 0x52, 0x8b, 0x8b, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x25, 0x65, 0x2e, 0x5e, 0xc7, 0xe4, 0xe4, 0xd4,
	0x02, 0xb8, 0x52, 0x21, 0x2e, 0x96, 0x82, 0xfc, 0xa2, 0x12, 0xb0, 0x3a, 0xd6, 0x20, 0x30, 0x5b,
	0x49, 0x97, 0x4b, 0xd0, 0x25, 0xb3, 0x38, 0x99, 0x04, 0x33, 0x83, 0x52, 0xb3, 0x90, 0x94, 0x62,
	0x31, 0xd3, 0x28, 0x11, 0xee, 0xc8, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x7f, 0x2e,
	0x76, 0xa8, 0x88, 0x90, 0x82, 0x1e, 0x86, 0x67, 0x51, 0x7d, 0x24, 0x45, 0x50, 0x85, 0x12, 0x43,
	0x12, 0x1b, 0x38, 0x80, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0x34, 0x77, 0x72, 0x3a,
	0x01, 0x00, 0x00,
}
